apiVersion: v1
kind: PersistentVolume
metadata:
  name: thumbnail-thumbnails
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.36.7.156"
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thumbnail-thumbnails
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi